import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import Link from 'next/link';
import HeroBanner from "./HeroBanner"
import LoversSection from './LoversSection'
import BannerCheckAvailability from './CheckAvailability'
// import DetailPagelisting from './DetailListing'
// import Travelingitinerary from "./TravelItinerary"
import Credit from './credit-payment'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>22-08-2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.css"/>
  

  
  {/* <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script> */}
  {/* <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script> */}

  {/* <script
    // you might need to get a newer version
    src="https://kit.fontawesome.com/fbadad80a0.js"
    crossOrigin="anonymous"
  ></script> */}
      </Head>

      <HeroBanner></HeroBanner>
      <LoversSection></LoversSection>
      {/* <BannerCheckAvailability></BannerCheckAvailability> */}
      {/* <DetailPagelisting></DetailPagelisting> */}
      {/* <Travelingitinerary></Travelingitinerary> */}
      <Credit></Credit>
      
      
      
      <main className={styles.main}>
        <div className={styles.description}>
        
        
        </div>

        <div className={styles.center}>
        
          <div className={styles.thirteen}>
            <Link href="/HeroBanner"><Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            /></Link>
          </div>
        </div>

        
      </main>
     
    </>
  )
}
