import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


import Link from 'next/link';
import HeroBanner from "./HeroBanner"
import LoversSection from './LoversSection'



const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
    
        <title>22-08-2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.css"/>
 
      </Head>

      <HeroBanner></HeroBanner>
      <LoversSection></LoversSection>    
     
    </>
  )
}
